### ISSUE TITLE
FOSDEM 2016 - collaborating on session "How do I contribute to FOSS"

### ISSUE THREAD

**Issue by ei8fdb** [opensourcedesign/events#30]
Hi all,

Happy Christmas/holidays/Hanukkah or just generally late December. :)

A few people proposed sessions which were very similar to the "how do I contribute to FOSS/how do I get designers interested in my project/how do I get developers interested in my design work" theme.

I suggested a proposal called how do I contribute. It is a panel made up of designers, researchers, and developers who are already working in open source software, and the discussion will focus on:

1) How to identify what project(s) you want to contribute to (What are you interested in?)
2) Where to find open source projects (Github, Sourceforge)
3) How to make the first connection with a project
4) How to make your first contribution. 

Are any of you interested in teaming up and using collective brain power and running the session together? 

I'd be very happy if the other session proposers would be the smart experienced panel speakers talking about their experience and advice.

Thoughts?

**Comment by jancborchardt** [comment]
@ei8fdb I’d be in for sure! Would also be cool to get someone who is mainly a developer / project maintainer, and also a designer with very little technical background. That way we can cover many angles.

**Comment by belenbarrospena** [comment]
@ei8fdb It might be a long shot, but maybe one of the engineers in my office, who have been developing open source for many years, and have also had the misfortune of having to work with me, might be willing to join the panel. I'll ask.

**Comment by jancborchardt** [comment]
> have also had the misfortune of having to work with me

:D

**Comment by ei8fdb** [comment]
On 29/12/2015 09:29, Belen Pena wrote:

> @ei8fdb It might be a long shot, but maybe one of the engineers in my
> office, who have been developing open source for many years, and have
> also had the misfortune of having to work with me, might be willing
> to join the panel. I'll ask.

Thanks, please ask him if he's willing to spill the beans.

**Comment by evalica** [comment]
Some ideas: 

1) How to identify what project(s) you want to contribute to
- What are you interested in? Where areas do you want to make contributions to? (Maybe you want to help with medical, astrological, botanical, musical projects = good causes or passions.)
- What projects do you use? (Particularly useful since you are already a target user, know the problems and it's easy to know what new functionality could be integrated.)
- What skills do you have? Pick projects that need design work? Do you have a preferred programming language (this could pre-filter the list of available projects)?
- Coolness factor (Maybe you are drawn towards famous projects: ubuntu, mozilla, etc. Another approach is to pick a trending project.)
- Innovation (Maybe you want to create your own open source project.)

2) Where to find open source projects (Github, Sourceforge)
- Notoriety (you just know about the project - now you just need to find the Getting Started guide)
- GitHub (https://github.com/explore, https://github.com/trending, https://github.com/showcases, etc.)
- Sourceforge (http://sourceforge.net/directory/)
- Apache (https://projects.apache.org/)
- etc.

3) How to make the first connection with a project
- Always look for Getting Started guides on the website or CONTRIBUTING.md on GitHub. They usually lists the preferred method for communication
- Check out the social mentions on the homepages (twitter, facebook, etc.) and ask there for directions
- Maybe you follow the blog of a core developer and you could ask him to introduce you to the project
- The majority of open source projects use IRC for direct communication
- If you need to be asynchronous, subscribe to the mailinglists and set up filters (maybe you are interested just in the design or CSS topics)

4) How to make your first contribution. 
- Several ways (Blogging, Giving feedback, Helping other users, Documentation, Translations, Design, Testing, Coding)
- Coding
  - Identify the bug tracker (in GitHub is integrated, but some projects could use independent trackers like Bugzilla, etc.)
  - Pick / raise an issue (you could look for simple issue using tracker filters, some projects provide Paper Cuts [selection of issues easy for beginners] or just report something you have found and know how to solve)
  - Pull Requests (https://help.github.com/articles/creating-a-pull-request/)
- Design
  - Propose a new feature or redesign a current functionality
  - Usually proposals are sent on the mailinglist, but some projects might have some other voting mechanisms

x) Success stories about successful contributions

**Comment by simonv3** [comment]
Thanks for that awesome list @evalica. Maybe some point in the future we could clean it up and write it as an article?

The format reminded me of this talk: https://shaunagm.github.io/personal/pycon2015.html#/

**Comment by jancborchardt** [comment]
Btw, for finding open source projects for a designer to start anew in, one of the most important aspects is that the project is welcoming to designers. A good place to find a project for that is http://opensourcedesign.net/jobs/ ;) (rather than just looking around randomly on Github etc)

**Comment by evalica** [comment]
@simonv3 Great slides - I didn't know about that talk and there are very interesting stuff listed. Regarding the article idea maybe we could transform the majority of talks we have at FOSDEM as articles on the blog, similar to the notes Roy took last year. 

@jancborchardt good point ;) we could put that first or last in the 2) point (in case Bernard wants to use some of the ideas).

**Comment by belenbarrospena** [comment]
@ei8fdb I asked some developers here if any of them would like to join the panel, but looks like most of them will not be at FOSDEM this year, so no luck.

**Comment by jancborchardt** [comment]
There will also be some other folks from ownCloud at FOSDEM (@karlitschek, @LukasReschke, @jospoortvliet & more?). Maybe one of them would like to participate in the panel as dev working on an open source project with a big focus on design. :)

**Comment by elioqoshi** [comment]
I'd be happy to talk about my experiences as a volunteer designer at Mozilla if you think that would fit :)
