### ISSUE TITLE
Proposal for FOSDEM 2017 accessibility devroom

### ISSUE THREAD

**Issue by ei8fdb** [opensourcedesign/events#42]
I saw a mail on the Mozilla a11y mailing list where this guy Jean-Philippe MENGUAL wanted to propose an accessibility devroom at FOSDEM. 

https://groups.google.com/forum/#!topic/mozilla.accessibility/EGZ0CuCoL-M

I followed up with him and he has submitted it. It seems he already has the speakers and subjects organised. 

They look like interesting topics anyway:
1. Why accessibility needs to make part of free software: Jean-Philippe MENGUAL
2. Technical general introduction: Samuel Thibault
3. The solutions in GUI: at-spi and derivatives (Alejandro Pinero)
4. Sending to assistive techno what's needed: Ma!io Lang
5. Shipping non-reg tests in unit tests: Samuel
6. Focus on Mozilla suite problems: discuss between Mozilla a11y
   responsible and a member of Hypra team and Samuel and anyone who want to
   help. Idea: identifying reported bugs and a process to help fixing them
   easily, even with volunteers.
7. Focus on LibreOffice: Michael Meeks, Jacob (Igalia) or other devs, a
   Rypra member, anyone to help. We'd introduce our full round of bugs, the
   LO online issue, and see what skills are needed to fix what and how we
   can catch them.
8. Focus on MATE: problems with 1.14, fixes, hacking, squphing  

---

I mentioned to him that we had a design and research room and said to get in touch if he wanted to. Fingers crossed the room gets accepted as there are some interesting subjects.

(EDITED: To make it clear that talk number "0" was being given by Jean-Philippe MENGUAL ("myself") and not me - ei8fdb!)

**Comment by belenbarrospena** [comment]
This is definitely good to see. It seems to me accessibility never gets the attention it deserves.

I find it a bit sad that they are not opening a public cfp though. It basically eliminates all chances of getting other voices heard. They will be the worst for it, since I am sure there is plenty of interesting accessibility work going on outside their circle.

Also, I don't know of any other devroom that does things like this: all the ones I know about open a cfp instead of deciding the content in advance. It's a bit strange.

Just my 2 cents.

**Comment by elioqoshi** [comment]
It's rather absurd to close up the process and curate the schedule that much in a FLOSS conference but yeah. I totally support the topics, but it's not well handled. What if someone else wants to speak about accessibility? They won't have the chance, because said developer room is already ready. Weird.

**Comment by ei8fdb** [comment]
@belenbarrospena I was going to make the point to them that they should open it to other speakers, but I don't know them....

@elioqoshi well, if someone wants to talk about a11y at FOSDEM, and they are not going to make an open CFP, I think we should advertise the fact we welcome a11y talks in our devroom too.

What do you think?

**Comment by elioqoshi** [comment]
Yeah, we should emphasize that in case there is anyone who feels left out. I have the leading a11y engineer at Mozilla in mind right now even. He was at FOSDEM 2 years ago.

**Comment by jancborchardt** [comment]
@ei8fdb @belenbarrospena @elioqoshi seems from https://fosdem.org/2017/news/2016-10-10-accepted-developer-rooms/ that their room was not accepted. Did you already contact them if they want to submit a talk to our room?

**Comment by ei8fdb** [comment]
@jancborchardt I cannot get my message sent to their list. I tried 3 times. Next year, I'd advertise our room again.

**Comment by ei8fdb** [comment]
I think we can close this now? If anyone wants to reopen it, please do.
