### ISSUE TITLE
OpenTechSummit Berlin-Potsdam, 25th May 2017

### ISSUE THREAD

**Issue by jancborchardt** [opensourcedesign/events#68]
On May 25th there will be [OpenTechSummit](http://opentechsummit.net/) in Berlin-Potsdam. I’m part of the organization team and there’s a track for Open Design & Libre Graphics.

The Call for Proposals has been extended until May 10: https://eventyay.com/e/5642d9a1/cfs/

cc @bnvk @Incabell @jdittrich @ScintillaLuz @Kriesse @gsambrotta @bbalazs @mrflix who are in Berlin and @elioqoshi who will also be there.

- Talk title @speaker-username
- Open Source Design – the community & existing projects (@jancborchardt)
- Mozilla Open Design (@elioqoshi)
- Wikimedia design? (@jdittrich @Incabell)
- Contextual groups in LibreOffice Notebookbar (@HeikoTietze)
- @simonv3?
- …

**Comment by elioqoshi** [comment]
Thanks @jancborchardt !

I applied with a Mozilla Open Design Talk and Workshop as well.
Is there a way we can help beyond submitting talks? Or should we get organized in a similar manner like FOSDEM?

**Comment by Incabell** [comment]
I haven't talked to @jdittrich yet but I think we'll likely apply with a talk/workshop there as well.

Also for me, I would be glad to help with organisation or whatever else there is to do.

**Comment by jancborchardt** [comment]
cc @jdittrich @bnvk @elioqoshi @Incabell @eppfel @simonv3 @guiguru @HeikoTietze @gsambrotta did you already apply? :)

Let me know what your talk is about, or update the original post above so we know who else is there. :) Then we can also create an event about it.

**Comment by jancborchardt** [comment]
And please spread the word on Twitter: https://twitter.com/opensrcdesign/status/859833270309199878 :) (and elsewhere of course too)

**Comment by simonv3** [comment]
I still have to confirm travel situations, but I plan on being there :)

If anyone has a couch I can stay on for a couple of days that would be awesome!

**Comment by HeikoTietze** [comment]
Tried to register but get an error on submit. My proposal is:

Title: Contextual groups in LibreOffice' Notebookbar
Short: The story behind LibreOffice' Notebookbars from a UX perspective will illustrate the need for requirements in Open Source Design.
Long: Toolbars are a common toolkit control that have been around since the dawn of GUI applications, providing direct access to an application's most frequently used functions. But with increasing scope, the number of frequently used functions grows to an extent that can have a detrimental impact on quickly locating a particular item. LibreOffice made it possible to create UI based toolbars on blank canvas where designers have all the freedom to do whatever they want with the space. The talk will present the reasoning behind the Notebookbar layout with contextual groups.
Talk: 00:25

This talk was held in Brussels first and I will update it slightly to cover the special interests of the design folks. In particular, it shows a lot about why having precise requirements is needed in Open Source.

**Comment by HeikoTietze** [comment]
Without comment and language it worked now. Draft is online at https://eventyay.com/events/mysessions/3616/

**Comment by evalica** [comment]
Closing as this event passed.
